### ISSUE TITLE
EAC

### ISSUE THREAD

**Issue by r4v3b0yy** [VityazevEgor/Rust-Fishing-Bot-GUI#1]
А бан не дадут за такое?)

**Comment by VityazevEgor** [comment]
На 02.07 аккаунт на котором я играл с этим ботом всё ещё жив. Если говорить о детектах, то это маловероятно, ведь всё что делает бот - это скриншоты и эмуляция мышки/клавиатуры через WinAPI. Он не читает память игры, бот получает данные читая текст с скриншотов и сравнивая цвета пикселей.
